### PR TITLE
Add a missing migration

### PR DESCRIPTION
**Pull request by rloomans**
Adds a missing migration so that Django doesn't complain

### CODE REVIEW

**Comment by adamalton** [comment]
Does this not do the same thing as migration 002?

**Comment by rloomans** [comment]
It does. Odd. 

I'll see if I can simply reproduce the issue I was seeing.

-- 
Robert Loomans
robert@loomans.org

**Comment by rloomans** [comment]
Only seems to happen to me occasionally with heroku... I can't reliably reproduce.

**Comment by rloomans** [comment]
Ok... I figured it out: Depending on whether you use python 2.x or 3.x it will interpret the the '-created' as unicode or bytestring.

**Pull request closed without merging**
