### PR TITLE
Add individual report fields

### LINKED ISSUE #14: Store record fields individually
CSP reports are stored as they came in, which makes it very impossible to filter using SQL.

I propose additional model fields:
* `valid` - whether CSP report is valid (i.e. can be split into fields)

CSP 1.0 fields according to https://www.w3.org/TR/2012/CR-CSP-20121115/#report-uri - will be NULL for invalid CSP reports
* `document_uri`
* `referrer`
* `blocked-uri`
* `violated-directive`
* `original-policy`

CSP 2.0 fields accoring to https://www.w3.org/TR/CSP2/#violation-reports - will be NULL for invalid CSP reports or if not present in the report
* `effective-directive`
* `status-code`
* `source-file`
* `line-number`
* `column-number`

CSP 3.0 fields https://www.w3.org/TR/CSP/#deprecated-serialize-violation
* `disposition` - will be NULL for invalid CSP reports or CSP < 3.0 reports

### PR DESCRIPTION
**Pull request by ziima**
Fixes #14

### CODE REVIEW

**Comment by adamalton** [comment]
Thanks for the work on this, it looks really good.  Just a couple of questions/points:

* What's the reason for putting `null=True` on the `TextField`s?  The Django docs [recommend against this](https://docs.djangoproject.com/en/1.11/ref/models/fields/#null), as they will default to an empty string anyway.
* I think we should probably put the `from_message` method on the manager class, rather than on the model class.  (To be consistent with other object creation methods in Django, e.g. `User.objects.create_user`.)

Other than those 2 minor things, this looks great!

**Comment by ziima** [comment]
* As noted in #14, NULL values state that a CSP report field is not valid and cannot be parsed. On the other hand, empty string can be valid value of the report field.
* In my understanding, the manager class handles interaction between the model and database, which is n the case for `from_message`. If we should turn the `from_message` into a manager method, I'd suggest to include the `save` and rename it to `create_from_message`.

**Comment by ziima** [comment]
Any further comments?

**Comment by adamalton** [comment]
Sorry, I went MIA there!

Your comments make sense.  Merging!...

**Comment by ziima** [comment]
Thanks!

**Pull request merged**
