### PR TITLE
Store user agent along with the report

### PR DESCRIPTION
**Pull request by ziima**
Store user agent headers to allow monitoring of troublesome browsers.

### CODE REVIEW

**Comment by adamalton** [comment]
This is cool, thanks.  My only request is that we don't have `null=True` on the `TextField` (my top pet hate in Django 😀 ).

**Comment by ziima** [comment]
I don't quite like the idea to store empty string in cases we don't know the value. NULL is in my opinion a correct value to be inserted in this case, whereas empty string will be put it, if the browser actually sends it (actually my top hate in Django before they started to respect the null value in forms).

However, I won't insist on it. Let me know whether you agree with the comment, or whether I should drop the null.

**Comment by adamalton** [comment]
As I understand it, Django doesn't support saving None via a form field (not without customisation) https://docs.djangoproject.com/en/1.11/ref/forms/fields/#django.forms.Field.required.

So if we have `null=True`, then any CSPReport edited via the Django admin could change from storing `None` to storing `""`.

I agree that storing `None` if the header is not present at all, and storing `""` if the header is sent as an empty value is a more "correct" way of doing it.  But if Django forms are potentially going to change the value anyway then we can end up implying that we differentiate between the two, but actually providing inaccurate data.

Obviously it's a minor thing.  I think we should base it on the behaviour of Django forms: if the forms allow saving `None` distinct from `""` then let's keep the `null=True`.  And if not then let's drop it.

**Comment by ziima** [comment]
Since 1.11 Django stores `NULL` in case CharField has `null=True`, see fifth item in https://docs.djangoproject.com/en/1.11/releases/1.11/#miscellaneous. But I tested it, and it still only works for models and not forms. I give up and wil drop the `null`.

By the way: should we actually allow users to modify CSPReports through admin interface? I would just let them see or delete the reports, but wouldn't allow them to add or change them.

**Comment by ziima** [comment]
Null dropped.

**Comment by adamalton** [comment]
> By the way: should we actually allow users to modify CSPReports through admin interface?

Good question!  I think it's probably not worth the effort to deliberately prevent it.

**Comment by adamalton** [comment]
Thanks! 🌻

**Pull request merged**
